version: "3"
services:
  weather_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - backend
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: weather
    networks:
      - backend
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
  
networks:
  backend:
    driver: bridge